---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      required: true
      description: User ID
      schema:
        type: integer
    get:
      summary: Retrieve all the posts of a user
      tags:
      - Posts
      responses:
        '200':
          description: OK
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
